export const ID_AUTH_PAGES = {
    CONNECT_WALLET: "ID_AUTH_PAGES_CONNECT_WALLET",
    PROFILE: "ID_AUTH_PAGES_PROFILE",
}

export const ID_BANKER_PAGES = {
    BANKER_MENU: "ID_BANKER_PAGES_BANKER_MENU",
    STAKE_READY: "ID_BANKER_PAGES_STAKE_READY",
    STAKE_LP: "ID_BANKER_PAGES_STAKE_LP",
}

export const ID_MARKETPLACE_PAGES = {
    MARKET_PLACE_MENU: "ID_MARKETPLACE_PAGES_MARKET_PLACE_MENU",
    BUY: "ID_MARKETPLACE_PAGES_BUY",
    BATCH_BUY: "ID_MARKETPLACE_PAGES_BATCH_BUY",
    SELL: "ID_MARKETPLACE_PAGES_SELL",
}

export const ID_MARKET_HOTSPOTS = {
    VENDOR: "ID_MARKET_HOTSPOTS_VENDOR",
    DEX: "ID_MARKET_HOTSPOTS_DEX",
    BANKER: "ID_MARKET_HOTSPOTS_BANKER",
    HELPER: "ID_MARKET_HOTSPOTS_HELPER",
    MARKET: "ID_MARKET_HOTSPOTS_MARKET",
    LEADERBOARD: "ID_MARKET_HOTSPOTS_LEADERBOARD",
    SAGE: "ID_MARKET_HOTSPOTS_SAGE",
}

export const ID_FARM_HOTSPOTS = {
    FARMER: "ID_FARM_HOTSPOTS_FARMER",
    VENDOR: "ID_MARKET_HOTSPOTS_VENDOR",
    DEX: "ID_MARKET_HOTSPOTS_DEX",
    BANKER: "ID_MARKET_HOTSPOTS_BANKER",
    HELPER: "ID_MARKET_HOTSPOTS_HELPER",
    MARKET: "ID_MARKET_HOTSPOTS_MARKET",
    LEADERBOARD: "ID_MARKET_HOTSPOTS_LEADERBOARD",
}

export const ID_SOCIAL = {
    TWITTER: "ID_SOCIAL_TWITTER",
    DISCORD: "ID_SOCIAL_DISCORD",
    TUTORIAL: "ID_SOCIAL_TUTORIAL",
}

export const ID_ITEM_CATEGORIES = {
    SEED: "ID_ITEM_SEED",
    PRODUCE: "ID_ITEM_CROP",
    POTION: "ID_ITEM_POTION",
    LOOT: "ID_ITEM_LOOT",
}

export const ID_RARE_TYPE = {
    COMMON: "ID_RARE_TYPE_COMMON",
    UNCOMMON: "ID_RARE_TYPE_UNCOMMON",
    RARE: "ID_RARE_TYPE_RARE",
    EPIC: "ID_RARE_TYPE_EPIC",
    LEGENDARY: "ID_RARE_TYPE_LEGENDARY",
}

export const ID_SEED_SHOP_PAGES = {
    SEED_PACK_LIST: "SEED_SHOP_PAGES_SEED_PACK_LIST",
    SEED_PACK_DETAIL: "SEED_SHOP_PAGES_SEED_PACK_DETAIL",
    ROLL_CHANCES: "SEED_SHOP_PAGES_ROLL_CHANCES",
    CUSTOM_AMOUNT: "SEED_SHOP_PAGES_CUSTOM_AMOUNT",
}

export const ID_CROP_CATEGORIES = {
    FEEBLE_SEED: "ID_CROP_FEEBLE_SEED",
    PICO_SEED: "ID_CROP_PICO_SEED",
    BASIC_SEED: "ID_CROP_BASIC_SEED",
    PREMIUM_SEED: "ID_CROP_PREMIUM_SEED",
}
const CAT_FEEBLE_SEED   = 1n << 248n;
const CAT_PICO_SEED     = 2n << 248n;
const CAT_BASIC_SEED    = 3n << 248n;
const CAT_PREMIUM_SEED  = 4n << 248n;
const CAT_PICO_PRODUCE   = 5n << 248n;
const CAT_BASIC_PRODUCE  = 6n << 248n;
const CAT_PREMIUM_PRODUCE = 7n << 248n;
const CAT_BAIT = 8n << 248n;
const CAT_FISH = 9n << 248n;
const CAT_CHEST = 10n << 248n;
const CAT_POTION = 11n << 248n;
export const ID_SEEDS = {
    F_POTATO: CAT_FEEBLE_SEED | 1n,
    F_LETTUCE: CAT_FEEBLE_SEED | 2n,
    F_CABBAGE: CAT_FEEBLE_SEED | 3n,
    F_ONION: CAT_FEEBLE_SEED | 4n,
    F_RADISH: CAT_FEEBLE_SEED | 5n,
    POTATO: CAT_PICO_SEED | 1n,
    LETTUCE: CAT_PICO_SEED | 2n,
    CABBAGE: CAT_PICO_SEED | 3n,
    ONION: CAT_PICO_SEED | 4n,
    RADISH: CAT_PICO_SEED | 5n,
    WHEAT: CAT_BASIC_SEED | 1n,
    TOMATO: CAT_BASIC_SEED | 2n,
    CARROT: CAT_BASIC_SEED | 3n,
    CORN: CAT_BASIC_SEED | 4n,
    PUMPKIN: CAT_BASIC_SEED | 5n,
    CHILI: CAT_BASIC_SEED | 6n,
    PARSNIP: CAT_BASIC_SEED | 7n,
    CELERY: CAT_BASIC_SEED | 8n,
    BROCCOLI: CAT_BASIC_SEED | 9n,
    CAULIFLOWER: CAT_BASIC_SEED | 10n,
    BERRY: CAT_BASIC_SEED | 11n,
    GRAPES: CAT_BASIC_SEED | 12n,
    BANANA: CAT_PREMIUM_SEED | 1n,
    MANGO: CAT_PREMIUM_SEED | 2n,
    AVOCADO: CAT_PREMIUM_SEED | 3n,
    PINEAPPLE: CAT_PREMIUM_SEED | 4n,
    BLUEBERRY: CAT_PREMIUM_SEED | 5n,
    ARTICHOKE: CAT_PREMIUM_SEED | 6n,
    PAPAYA: CAT_PREMIUM_SEED | 7n,
    FIG: CAT_PREMIUM_SEED | 8n,
    LICHI: CAT_PREMIUM_SEED | 9n,
    LAVENDER: CAT_PREMIUM_SEED | 10n,
    DRAGON_FRUIT: CAT_PREMIUM_SEED | 11n,
}

export const ID_PRODUCE_ITEMS = {
    // Pico Produce
    POTATO: CAT_PICO_PRODUCE | 1n,
    LETTUCE: CAT_PICO_PRODUCE | 2n,
    CABBAGE: CAT_PICO_PRODUCE | 3n,
    ONION: CAT_PICO_PRODUCE | 4n,
    RADISH: CAT_PICO_PRODUCE | 5n,

    // Basic Produce
    WHEAT: CAT_BASIC_PRODUCE | 1n,
    TOMATO: CAT_BASIC_PRODUCE | 2n,
    CARROT: CAT_BASIC_PRODUCE | 3n,
    CORN: CAT_BASIC_PRODUCE | 4n,
    PUMPKIN: CAT_BASIC_PRODUCE | 5n,
    CHILI: CAT_BASIC_PRODUCE | 6n,
    PARSNAP: CAT_BASIC_PRODUCE | 7n,
    CELERY: CAT_BASIC_PRODUCE | 8n,
    BROCCOLI: CAT_BASIC_PRODUCE | 9n,
    CAULIFLOWER: CAT_BASIC_PRODUCE | 10n,
    BERRY: CAT_BASIC_PRODUCE | 11n,
    GRAPES: CAT_BASIC_PRODUCE | 12n,

    // Premium Produce
    BANANA: CAT_PREMIUM_PRODUCE | 1n,
    MANGO: CAT_PREMIUM_PRODUCE | 2n,
    AVOCADO: CAT_PREMIUM_PRODUCE | 3n,
    PINEAPPLE: CAT_PREMIUM_PRODUCE | 4n,
    BLUEBERRY: CAT_PREMIUM_PRODUCE | 5n,
    ARTICHOKE: CAT_PREMIUM_PRODUCE | 6n,
    PAPAYA: CAT_PREMIUM_PRODUCE | 7n,
    FIG: CAT_PREMIUM_PRODUCE | 8n,
    LYCHEE: CAT_PREMIUM_PRODUCE | 9n,
    LAVENDER: CAT_PREMIUM_PRODUCE | 10n,
    DRAGONFRUIT: CAT_PREMIUM_PRODUCE | 11n,
}

export const ID_BAIT_ITEMS = {
    BAIT_1: CAT_BAIT | 1n,
    BAIT_2: CAT_BAIT | 2n,
    BAIT_3: CAT_BAIT | 3n,
}

export const ID_FISH_ITEMS = {
    FISH_SMALL: CAT_FISH | 1n,
    FISH_LARGE: CAT_FISH | 2n,
}

export const ID_CHEST_ITEMS = {
    CHEST_WOOD: CAT_CHEST | 1n,
    CHEST_BRONZE: CAT_CHEST | 2n,
    CHEST_SILVER: CAT_CHEST | 3n,
    CHEST_GOLD: CAT_CHEST | 4n,
}

export const ID_POTION_ITEMS = {
    POTION_GROWTH_ELIXIR: CAT_POTION | 1n,
    POTION_PESTICIDE: CAT_POTION | 2n,
    POTION_FERTILIZER: CAT_POTION | 3n,
}

export const ID_POTION_CATEGORIES = {
    GROWTH_ELIXIR: "ID_POTION_TYPE_GROWTH_ELIXIRS",
    FERTILIZER: "ID_POTION_TYPE_FERTILIZERS",
    PESTICIDE: "ID_POTION_TYPE_PESTICIDES",
}

export const ID_POTIONS = {
    GROWTH_ELIXIR: "ID_POTION_GROWTH_ELIXIR",
    GROWTH_ELIXIR_II: "ID_POTION_GROWTH_ELIXIR_II",
    GROWTH_ELIXIR_III: "ID_POTION_GROWTH_ELIXIR_III",
    FERTILIZER: "ID_POTION_FERTILIZER",
    FERTILIZER_II: "ID_POTION_FERTILIZER_II",
    FERTILIZER_III: "ID_POTION_FERTILIZER_III",
    PESTICIDE: "ID_POTION_PESTICIDE",
    PESTICIDE_II: "ID_POTION_PESTICIDE_II",
    PESTICIDE_III: "ID_POTION_PESTICIDE_III",
}

export const ID_LOOT_CATEGORIES = {
    CHEST: "ID_LOOT_CATEGORY_CHEST",
    BAIT: "ID_LOOT_CATEGORY_BAIT",
    FISH: "ID_LOOT_CATEGORY_FISH",
    MISC: "ID_LOOT_CATEGORY_MISC"
}

export const ID_LOOTS = {
    WOODEN_CHEST: "ID_LOOT_WOODEN_CHEST",
    BRONZE_CHEST: "ID_LOOT_BRONZE_CHEST",
    SILVER_CHEST: "ID_LOOT_SILVER_CHEST",
    GOLDEN_CHEST: "ID_LOOT_GOLDEN_CHEST",
    PLATINUM_CHEST: "ID_LOOT_PLATINUM_CHEST",
    BAIT_I: "ID_LOOT_BAIT_I",
    BAIT_II: "ID_LOOT_BAIT_II",
    BAIT_III: "ID_LOOT_BAIT_III",
    ANCHOVY: "ID_LOOT_ANCHOVY",
    SARDINE: "ID_LOOT_SARDINE",
    HERRING: "ID_LOOT_HERRING",
    SMALL_TROUT: "ID_LOOT_SMALL_TROUT",
    YELLOW_PERCH: "ID_LOOT_YELLOW_PERCH",
    SALMON: "ID_LOOT_SALMON",
    ORANGE_ROUGHY: "ID_LOOT_ORANGE_ROUGHY",
    CATFISH: "ID_LOOT_CATFISH",
    SMALL_SHARK: "ID_LOOT_SMALL_SHARK",
    LIFE_BUD: "ID_LOOT_LIFE_BUD",
}