export const ID_AUTH_PAGES = {
    CONNECT_WALLET: "ID_AUTH_PAGES_CONNECT_WALLET",
    PROFILE: "ID_AUTH_PAGES_PROFILE",
}

export const ID_BANKER_PAGES = {
    BANKER_MENU: "ID_BANKER_PAGES_BANKER_MENU",
    STAKE_HONEY: "ID_BANKER_PAGES_STAKE_HONEY",
    STAKE_LP: "ID_BANKER_PAGES_STAKE_LP",
}

export const ID_MARKETPLACE_PAGES = {
    MARKET_PLACE_MENU: "ID_MARKETPLACE_PAGES_MARKET_PLACE_MENU",
    BUY: "ID_MARKETPLACE_PAGES_BUY",
    BATCH_BUY: "ID_MARKETPLACE_PAGES_BATCH_BUY",
    SELL: "ID_MARKETPLACE_PAGES_SELL",
}

export const ID_SAGE_PAGES = {
    SAGE_MENU: "ID_SAGE_MENU",
    WEEKLY_WAGE: "ID_WEEKLY_WAGE",
    WEEKLY_HARVEST: "ID_WEEKLY_HARVEST",
}

export const ID_ANGLER_PAGES = {
    ANGLER_MENU: "ID_ANGLER_MENU",
    START_FISHING: "ID_ANGLER_START_FISHING",
    CRAFT_BAIT: "ID_ANGLER_CRAFT_BAIT",
    FISHING: "ID_ANGLER_FISHING"
}

export const ID_INVENTORY_MENUS = {
    SEEDS: "ID_INVENTORY_MENUS_SEEDS",
    PRODUCE: "ID_INVENTORY_MENUS_PRODUCE",
    FISHES: "ID_INVENTORY_MENUS_FISHES",
    ITEMS: "ID_INVENTORY_MENUS_ITEMS",
}

export const ID_MARKET_HOTSPOTS = {
    VENDOR: "ID_MARKET_HOTSPOTS_VENDOR",
    DEX: "ID_MARKET_HOTSPOTS_DEX",
    BANKER: "ID_MARKET_HOTSPOTS_BANKER",
    HELPER: "ID_MARKET_HOTSPOTS_HELPER",
    MARKET: "ID_MARKET_HOTSPOTS_MARKET",
    LEADERBOARD: "ID_MARKET_HOTSPOTS_LEADERBOARD",
    SAGE: "ID_MARKET_HOTSPOTS_SAGE",
}

export const ID_FARM_HOTSPOTS = {
    FARMER: "ID_FARM_HOTSPOTS_FARMER",
    VENDOR: "ID_MARKET_HOTSPOTS_VENDOR",
    DEX: "ID_MARKET_HOTSPOTS_DEX",
    BANKER: "ID_MARKET_HOTSPOTS_BANKER",
    HELPER: "ID_MARKET_HOTSPOTS_HELPER",
    MARKET: "ID_MARKET_HOTSPOTS_MARKET",
    LEADERBOARD: "ID_MARKET_HOTSPOTS_LEADERBOARD",
}

export const ID_HOUSE_HOTSPOTS = {
    GOLD: "ID_HOUSE_HOTSPOTS_GOLD",
    ANGLER: "ID_HOUSE_HOTSPOTS_ANGLER",
    GOLD_CHEST: "ID_HOUSE_HOTSPOTS_GOLD_CHEST",
    GARDNER: "ID_HOUSE_HOTSPOTS_GARDNER",
    REFERRALS: "ID_HOUSE_HOTSPOTS_REFERRALS",
}

export const ID_TAVERN_HOTSPOTS = {
    POTION: "ID_TAVERN_HOTSPOTS_POTION",
}

export const ID_VALLEY_HOTSPOTS = {
    HOUSE: "ID_VALLEY_HOTSPOTS_HOUSE",
    FARM: "ID_VALLEY_HOTSPOTS_FARM",
    MARKET: "ID_VALLEY_HOTSPOTS_MARKET",
    TAVERN: "ID_VALLEY_HOTSPOTS_TAVERN",
    HERMITS_CAVE: "ID_VALLEY_HOTSPOTS_HERMITS_CAVE",
}

export const ID_SOCIAL = {
    TWITTER: "ID_SOCIAL_TWITTER",
    DISCORD: "ID_SOCIAL_DISCORD",
    TUTORIAL: "ID_SOCIAL_TUTORIAL",
}

export const ID_ITEM_CATEGORIES = {
    SEED: "ID_ITEM_SEED",
    PRODUCE: "ID_ITEM_CROP",
    POTION: "ID_ITEM_POTION",
    LOOT: "ID_ITEM_LOOT",
}

export const ID_RARE_TYPE = {
    COMMON: "ID_RARE_TYPE_COMMON",
    UNCOMMON: "ID_RARE_TYPE_UNCOMMON",
    RARE: "ID_RARE_TYPE_RARE",
    EPIC: "ID_RARE_TYPE_EPIC",
    LEGENDARY: "ID_RARE_TYPE_LEGENDARY",
}

export const ID_SEED_SHOP_PAGES = {
    SEED_PACK_LIST: "SEED_SHOP_PAGES_SEED_PACK_LIST",
    SEED_PACK_DETAIL: "SEED_SHOP_PAGES_SEED_PACK_DETAIL",
    ROLL_CHANCES: "SEED_SHOP_PAGES_ROLL_CHANCES",
    CUSTOM_AMOUNT: "SEED_SHOP_PAGES_CUSTOM_AMOUNT",
}

export const ID_CROP_CATEGORIES = {
    FEEBLE_SEED: "ID_CROP_FEEBLE_SEED",
    PICO_SEED: "ID_CROP_PICO_SEED",
    BASIC_SEED: "ID_CROP_BASIC_SEED",
    PREMIUM_SEED: "ID_CROP_PREMIUM_SEED",
}
const CAT_FEEBLE_SEED = 1;
const CAT_PICO_SEED = 2;
const CAT_BASIC_SEED = 3;
const CAT_PREMIUM_SEED = 4;
const CAT_PICO_PRODUCE = 5;
const CAT_BASIC_PRODUCE = 6;
const CAT_PREMIUM_PRODUCE = 7;
const CAT_BAIT = 8;
const CAT_FISH = 9;
const CAT_CHEST = 10;
const CAT_POTION = 11;
export const ID_SEEDS = {
    F_POTATO: CAT_FEEBLE_SEED << 8 | 1,
    F_LETTUCE: CAT_FEEBLE_SEED << 8 | 2,
    F_CABBAGE: CAT_FEEBLE_SEED << 8 | 3,
    F_ONION: CAT_FEEBLE_SEED << 8 | 4,
    F_RADISH: CAT_FEEBLE_SEED << 8 | 5,
    POTATO: CAT_PICO_SEED << 8 | 1,
    LETTUCE: CAT_PICO_SEED << 8 | 2,
    CABBAGE: CAT_PICO_SEED << 8 | 3,
    ONION: CAT_PICO_SEED << 8 | 4,
    RADISH: CAT_PICO_SEED << 8 | 5,
    WHEAT: CAT_BASIC_SEED << 8 | 1,
    TOMATO: CAT_BASIC_SEED << 8 | 2,
    CARROT: CAT_BASIC_SEED << 8 | 3,
    CORN: CAT_BASIC_SEED << 8 | 4,
    PUMPKIN: CAT_BASIC_SEED << 8 | 5,
    CHILI: CAT_BASIC_SEED << 8 | 6,
    PARSNIP: CAT_BASIC_SEED << 8 | 7,
    CELERY: CAT_BASIC_SEED << 8 | 8,
    BROCCOLI: CAT_BASIC_SEED << 8 | 9,
    CAULIFLOWER: CAT_BASIC_SEED << 8 | 10,
    BERRY: CAT_BASIC_SEED << 8 | 11,
    GRAPES: CAT_BASIC_SEED << 8 | 12,
    BANANA: CAT_PREMIUM_SEED << 8 | 1,
    MANGO: CAT_PREMIUM_SEED << 8 | 2,
    AVOCADO: CAT_PREMIUM_SEED << 8 | 3,
    PINEAPPLE: CAT_PREMIUM_SEED << 8 | 4,
    BLUEBERRY: CAT_PREMIUM_SEED << 8 | 5,
    ARTICHOKE: CAT_PREMIUM_SEED << 8 | 6,
    PAPAYA: CAT_PREMIUM_SEED << 8 | 7,
    FIG: CAT_PREMIUM_SEED << 8 | 8,
    LICHI: CAT_PREMIUM_SEED << 8 | 9,
    LAVENDER: CAT_PREMIUM_SEED << 8 | 10,
    DRAGON_FRUIT: CAT_PREMIUM_SEED << 8 | 11,
}

export const ID_PRODUCE_ITEMS = {
    // Pico Produce
    POTATO: CAT_PICO_PRODUCE << 8 | 1,
    LETTUCE: CAT_PICO_PRODUCE << 8 | 2,
    CABBAGE: CAT_PICO_PRODUCE << 8 | 3,
    ONION: CAT_PICO_PRODUCE << 8 | 4,
    RADISH: CAT_PICO_PRODUCE << 8 | 5,

    // Basic Produce
    WHEAT: CAT_BASIC_PRODUCE << 8 | 1,
    TOMATO: CAT_BASIC_PRODUCE << 8 | 2,
    CARROT: CAT_BASIC_PRODUCE << 8 | 3,
    CORN: CAT_BASIC_PRODUCE << 8 | 4,
    PUMPKIN: CAT_BASIC_PRODUCE << 8 | 5,
    CHILI: CAT_BASIC_PRODUCE << 8 | 6,
    PARSNAP: CAT_BASIC_PRODUCE << 8 | 7,
    CELERY: CAT_BASIC_PRODUCE << 8 | 8,
    BROCCOLI: CAT_BASIC_PRODUCE << 8 | 9,
    CAULIFLOWER: CAT_BASIC_PRODUCE << 8 | 10,
    BERRY: CAT_BASIC_PRODUCE << 8 | 11,
    GRAPES: CAT_BASIC_PRODUCE << 8 | 12,

    // Premium Produce
    BANANA: CAT_PREMIUM_PRODUCE << 8 | 1,
    MANGO: CAT_PREMIUM_PRODUCE << 8 | 2,
    AVOCADO: CAT_PREMIUM_PRODUCE << 8 | 3,
    PINEAPPLE: CAT_PREMIUM_PRODUCE << 8 | 4,
    BLUEBERRY: CAT_PREMIUM_PRODUCE << 8 | 5,
    ARTICHOKE: CAT_PREMIUM_PRODUCE << 8 | 6,
    PAPAYA: CAT_PREMIUM_PRODUCE << 8 | 7,
    FIG: CAT_PREMIUM_PRODUCE << 8 | 8,
    LYCHEE: CAT_PREMIUM_PRODUCE << 8 | 9,
    LAVENDER: CAT_PREMIUM_PRODUCE << 8 | 10,
    DRAGONFRUIT: CAT_PREMIUM_PRODUCE << 8 | 11,
}

export const ID_BAIT_ITEMS = {
    BAIT_1: CAT_BAIT << 8 | 1,
    BAIT_2: CAT_BAIT << 8 | 2,
    BAIT_3: CAT_BAIT << 8 | 3,
}

export const ID_FISH_ITEMS = {
    FISH_SMALL: CAT_FISH << 8 | 1,
    FISH_LARGE: CAT_FISH << 8 | 2,
    ANCHOVY: CAT_FISH << 8 | 3,
    SARDINE: CAT_FISH << 8 | 4,
    HERRING: CAT_FISH << 8 | 5,
    SMALL_TROUT: CAT_FISH << 8 | 6,
    YELLOW_PERCH: CAT_FISH << 8 | 7,
    SALMON: CAT_FISH << 8 | 8,
    ORANGE_ROUGHY: CAT_FISH << 8 | 9,
    CATFISH: CAT_FISH << 8 | 10,
    SMALL_SHARK: CAT_FISH << 8 | 11,
}

export const ID_CHEST_ITEMS = {
    CHEST_WOOD: CAT_CHEST << 8 | 1,
    CHEST_BRONZE: CAT_CHEST << 8 | 2,
    CHEST_SILVER: CAT_CHEST << 8 | 3,
    CHEST_GOLD: CAT_CHEST << 8 | 4,
}

export const ID_POTION_ITEMS = {
    POTION_GROWTH_ELIXIR: CAT_POTION << 8 | 1,
    POTION_PESTICIDE: CAT_POTION << 8 | 2,
    POTION_FERTILIZER: CAT_POTION << 8 | 3,
    POTION_GROWTH_ELIXIR_II: CAT_POTION << 8 | 4,
    POTION_PESTICIDE_II: CAT_POTION << 8 | 5,
    POTION_FERTILIZER_II: CAT_POTION << 8 | 6,
    POTION_GROWTH_ELIXIR_III: CAT_POTION << 8 | 7,
    POTION_PESTICIDE_III: CAT_POTION << 8 | 8,
    POTION_FERTILIZER_III: CAT_POTION << 8 | 9,
}

export const ID_POTION_CATEGORIES = {
    GROWTH_ELIXIR: "ID_POTION_CATEGORIES_GROWTH_ELIXIR",
    PESTICIDE: "ID_POTION_CATEGORIES_PESTICIDE",
    FERTILIZER: "ID_POTION_CATEGORIES_FERTILIZER",
}

export const ID_MISC_ITEMS = {
    LIFE_BUD: "ID_LOOT_LIFE_BUD",
}

export const ID_LOOT_CATEGORIES = {
    CHEST: "ID_LOOT_CATEGORY_CHEST",
    BAIT: "ID_LOOT_CATEGORY_BAIT",
    FISH: "ID_LOOT_CATEGORY_FISH",
    MISC: "ID_LOOT_CATEGORY_MISC",
}

export const ID_FISHING_RODS = {
    LVL1: "ID_FISHING_ROD_1",
    LVL2: "ID_FISHING_ROD_2",
    LVL3: "ID_FISHING_ROD_3",
    LVL4: "ID_FISHING_ROD_4",
    LVL5: "ID_FISHING_ROD_5",
}