import { baitImages, chestImages, fishImages, fishingRodImages, potionImages } from "./_baseimages";
import { ID_SEEDS, ID_PRODUCE_ITEMS, ID_BAIT_ITEMS, ID_FISH_ITEMS, ID_CHEST_ITEMS, ID_POTION_ITEMS, ID_CROP_CATEGORIES, ID_RARE_TYPE, ID_ITEM_CATEGORIES, ID_POTION_CATEGORIES, ID_POTIONS, ID_LOOT_CATEGORIES, ID_LOOTS, ID_FISHING_RODS } from "./app_ids";

export const IMAGE_URL_CROP = "/public/images/crops/seeds.png";
// All items data with categories
export const ALL_ITEMS = {
  // Seeds
  [ID_SEEDS.F_POTATO]: {
    id: ID_SEEDS.F_POTATO,
    label: "F.POTATO",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.FEEBLE_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 29,
    honey: 0.5,
    lockedHoney: 0.75,
  },
  [ID_SEEDS.F_LETTUCE]: {
    id: ID_SEEDS.F_LETTUCE,
    label: "F.LETTUCE",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.FEEBLE_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 30,
    honey: 0.9,
    lockedHoney: 1.35,
  },
  [ID_SEEDS.F_CABBAGE]: {
    id: ID_SEEDS.F_CABBAGE,
    label: "F.CABBAGE",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.FEEBLE_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 31,
    honey: 1.2,
    lockedHoney: 1.8,
  },
  [ID_SEEDS.F_ONION]: {
    id: ID_SEEDS.F_ONION,
    label: "F.ONION",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.FEEBLE_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 32,
    honey: 2,
    lockedHoney: 3,
  },
  [ID_SEEDS.F_RADISH]: {
    id: ID_SEEDS.F_RADISH,
    label: "F.RADISH",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.FEEBLE_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 33,
    honey: 5.4,
    lockedHoney: 8.1,
  },
  [ID_SEEDS.POTATO]: {
    id: ID_SEEDS.POTATO,
    label: "POTATO",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 24,
    honey: 10,
    lockedHoney: 15,
  },
  [ID_SEEDS.LETTUCE]: {
    id: ID_SEEDS.LETTUCE,
    label: "LETTUCE",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 25,
    honey: 18,
    lockedHoney: 27,
  },
  [ID_SEEDS.CABBAGE]: {
    id: ID_SEEDS.CABBAGE,
    label: "CABBAGE",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 26,
    honey: 24,
    lockedHoney: 36,
  },
  [ID_SEEDS.ONION]: {
    id: ID_SEEDS.ONION,
    label: "ONION",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 27,
    honey: 40,
    lockedHoney: 60,
  },
  [ID_SEEDS.RADISH]: {
    id: ID_SEEDS.RADISH,
    label: "RADISH",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 28,
    honey: 108,
    lockedHoney: 162,
  },
  [ID_SEEDS.WHEAT]: {
    id: ID_SEEDS.WHEAT,
    label: "WHEAT",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 1,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_SEEDS.TOMATO]: {
    id: ID_SEEDS.TOMATO,
    label: "TOMATO",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 2,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_SEEDS.CARROT]: {
    id: ID_SEEDS.CARROT,
    label: "CARROT",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 3,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_SEEDS.CORN]: {
    id: ID_SEEDS.CORN,
    label: "CORN",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 4,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_SEEDS.PUMPKIN]: {
    id: ID_SEEDS.PUMPKIN,
    label: "PUMPKIN",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 5,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_SEEDS.CHILI]: {
    id: ID_SEEDS.CHILI,
    label: "CHILI",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 6,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_SEEDS.PARSNIP]: {
    id: ID_SEEDS.PARSNIP,
    label: "PARSNIP",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 7,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_SEEDS.CELERY]: {
    id: ID_SEEDS.CELERY,
    label: "CELERY",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 8,
    honey: 120,
    lockedHoney: 180,
  },
  [ID_SEEDS.BROCCOLI]: {
    id: ID_SEEDS.BROCCOLI,
    label: "BROCCOLI",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 9,
    honey: 120,
    lockedHoney: 180,
  },
  [ID_SEEDS.CAULIFLOWER]: {
    id: ID_SEEDS.CAULIFLOWER,
    label: "CAULIFLOWER",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 10,
    honey: 200,
    lockedHoney: 300,
  },
  [ID_SEEDS.BERRY]: {
    id: ID_SEEDS.BERRY,
    label: "BERRY",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 11,
    honey: 200,
    lockedHoney: 300,
  },
  [ID_SEEDS.GRAPES]: {
    id: ID_SEEDS.GRAPES,
    label: "GRAPES",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 12,
    honey: 540,
    lockedHoney: 810,
  },
  [ID_SEEDS.BANANA]: {
    id: ID_SEEDS.BANANA,
    label: "BANANA",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 13,
    honey: 400,
    lockedHoney: 600,
  },
  [ID_SEEDS.MANGO]: {
    id: ID_SEEDS.MANGO,
    label: "MANGO",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 14,
    honey: 400,
    lockedHoney: 600,
  },
  [ID_SEEDS.AVOCADO]: {
    id: ID_SEEDS.AVOCADO,
    label: "AVOCADO",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 15,
    honey: 400,
    lockedHoney: 600,
  },
  [ID_SEEDS.PINEAPPLE]: {
    id: ID_SEEDS.PINEAPPLE,
    label: "PINEAPPLE",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 16,
    honey: 720,
    lockedHoney: 1080,
  },
  [ID_SEEDS.BLUEBERRY]: {
    id: ID_SEEDS.BLUEBERRY,
    label: "BLUEBERRY",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 17,
    honey: 720,
    lockedHoney: 1080,
  },
  [ID_SEEDS.ARTICHOKE]: {
    id: ID_SEEDS.ARTICHOKE,
    label: "ARTICHOKE",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 18,
    honey: 720,
    lockedHoney: 1080,
  },
  [ID_SEEDS.PAPAYA]: {
    id: ID_SEEDS.PAPAYA,
    label: "PAPAYA",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 19,
    honey: 960,
    lockedHoney: 1440,
  },
  [ID_SEEDS.FIG]: {
    id: ID_SEEDS.FIG,
    label: "FIG",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 20,
    honey: 960,
    lockedHoney: 1440,
  },
  [ID_SEEDS.LICHI]: {
    id: ID_SEEDS.LICHI,
    label: "LICHI",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 21,
    honey: 1600,
    lockedHoney: 2400,
  },
  [ID_SEEDS.LAVENDER]: {
    id: ID_SEEDS.LAVENDER,
    label: "LAVENDER",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 22,
    honey: 1600,
    lockedHoney: 2400,
  },
  [ID_SEEDS.DRAGON_FRUIT]: {
    id: ID_SEEDS.DRAGON_FRUIT,
    label: "DRAGON_FRUIT",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 23,
    honey: 4400,
    lockedHoney: 6600,
  },

  // Produce items
  [ID_PRODUCE_ITEMS.POTATO]: {
    id: ID_PRODUCE_ITEMS.POTATO,
    label: "Potato",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 24,
    honey: 10,
    lockedHoney: 15,
  },
  [ID_PRODUCE_ITEMS.LETTUCE]: {
    id: ID_PRODUCE_ITEMS.LETTUCE,
    label: "Lettuce",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 25,
    honey: 18,
    lockedHoney: 27,
  },
  [ID_PRODUCE_ITEMS.CABBAGE]: {
    id: ID_PRODUCE_ITEMS.CABBAGE,
    label: "Cabbage",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 26,
    honey: 24,
    lockedHoney: 36,
  },
  [ID_PRODUCE_ITEMS.ONION]: {
    id: ID_PRODUCE_ITEMS.ONION,
    label: "Onion",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 27,
    honey: 40,
    lockedHoney: 60,
  },
  [ID_PRODUCE_ITEMS.RADISH]: {
    id: ID_PRODUCE_ITEMS.RADISH,
    label: "Radish",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 28,
    honey: 108,
    lockedHoney: 162,
  },
  [ID_PRODUCE_ITEMS.WHEAT]: {
    id: ID_PRODUCE_ITEMS.WHEAT,
    label: "Wheat",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 1,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_PRODUCE_ITEMS.TOMATO]: {
    id: ID_PRODUCE_ITEMS.TOMATO,
    label: "Tomato",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 2,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_PRODUCE_ITEMS.CARROT]: {
    id: ID_PRODUCE_ITEMS.CARROT,
    label: "Carrot",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 3,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_PRODUCE_ITEMS.CORN]: {
    id: ID_PRODUCE_ITEMS.CORN,
    label: "Corn",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 4,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_PRODUCE_ITEMS.PUMPKIN]: {
    id: ID_PRODUCE_ITEMS.PUMPKIN,
    label: "Pumpkin",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 5,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_PRODUCE_ITEMS.CHILI]: {
    id: ID_PRODUCE_ITEMS.CHILI,
    label: "Chili",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 6,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_PRODUCE_ITEMS.PARSNAP]: {
    id: ID_PRODUCE_ITEMS.PARSNAP,
    label: "Parnship",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 7,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_PRODUCE_ITEMS.CELERY]: {
    id: ID_PRODUCE_ITEMS.CELERY,
    label: "Celery",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 8,
    honey: 120,
    lockedHoney: 180,
  },
  [ID_PRODUCE_ITEMS.BROCCOLI]: {
    id: ID_PRODUCE_ITEMS.BROCCOLI,
    label: "Broccoli",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 9,
    honey: 120,
    lockedHoney: 180,
  },
  [ID_PRODUCE_ITEMS.CAULIFLOWER]: {
    id: ID_PRODUCE_ITEMS.CAULIFLOWER,
    label: "Cauliflower",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 10,
    honey: 200,
    lockedHoney: 300,
  },
  [ID_PRODUCE_ITEMS.BERRY]: {
    id: ID_PRODUCE_ITEMS.BERRY,
    label: "Berry",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 11,
    honey: 200,
    lockedHoney: 300,
  },
  [ID_PRODUCE_ITEMS.GRAPES]: {
    id: ID_PRODUCE_ITEMS.GRAPES,
    label: "Grapes",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 12,
    honey: 540,
    lockedHoney: 810,
  },
  [ID_PRODUCE_ITEMS.BANANA]: {
    id: ID_PRODUCE_ITEMS.BANANA,
    label: "Banana",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 13,
    honey: 400,
    lockedHoney: 600,
  },
  [ID_PRODUCE_ITEMS.MANGO]: {
    id: ID_PRODUCE_ITEMS.MANGO,
    label: "Mango",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 14,
    honey: 400,
    lockedHoney: 600,
  },
  [ID_PRODUCE_ITEMS.AVOCADO]: {
    id: ID_PRODUCE_ITEMS.AVOCADO,
    label: "Avocado",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 15,
    honey: 400,
    lockedHoney: 600,
  },
  [ID_PRODUCE_ITEMS.PINEAPPLE]: {
    id: ID_PRODUCE_ITEMS.PINEAPPLE,
    label: "Pineapple",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 16,
    honey: 720,
    lockedHoney: 1080,
  },
  [ID_PRODUCE_ITEMS.BLUEBERRY]: {
    id: ID_PRODUCE_ITEMS.BLUEBERRY,
    label: "Blueberry",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 17,
    honey: 720,
    lockedHoney: 1080,
  },
  [ID_PRODUCE_ITEMS.ARTICHOKE]: {
    id: ID_PRODUCE_ITEMS.ARTICHOKE,
    label: "Artichoke",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 18,
    honey: 720,
    lockedHoney: 1080,
  },
  [ID_PRODUCE_ITEMS.PAPAYA]: {
    id: ID_PRODUCE_ITEMS.PAPAYA,
    label: "Papaya",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 19,
    honey: 960,
    lockedHoney: 1440,
  },
  [ID_PRODUCE_ITEMS.FIG]: {
    id: ID_PRODUCE_ITEMS.FIG,
    label: "Fig",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 20,
    honey: 960,
    lockedHoney: 1440,
  },
  [ID_PRODUCE_ITEMS.LYCHEE]: {
    id: ID_PRODUCE_ITEMS.LYCHEE,
    label: "Lichi",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 21,
    honey: 1600,
    lockedHoney: 2400,
  },
  [ID_PRODUCE_ITEMS.LAVENDER]: {
    id: ID_PRODUCE_ITEMS.LAVENDER,
    label: "Lavender",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 22,
    honey: 1600,
    lockedHoney: 2400,
  },
  [ID_PRODUCE_ITEMS.DRAGONFRUIT]: {
    id: ID_PRODUCE_ITEMS.DRAGONFRUIT,
    label: "Dragon Fruit",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 23,
    honey: 4400,
    lockedHoney: 6600,
  },

  // Bait items
  [ID_BAIT_ITEMS.BAIT_1]: {
    id: ID_BAIT_ITEMS.BAIT_1,
    label: "Bait I",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.BAIT,
    type: ID_RARE_TYPE.COMMON,
    image: baitImages.bait1,
    honey: 0,
    lockedHoney: 0,
  },
  [ID_BAIT_ITEMS.BAIT_2]: {
    label: "Bait II",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.BAIT,
    type: ID_RARE_TYPE.UNCOMMON,
    image: baitImages.bait2,
    honey: 0,
    lockedHoney: 0,
  },
  [ID_BAIT_ITEMS.BAIT_3]: {
    label: "Bait_III",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.BAIT,
    type: ID_RARE_TYPE.RARE,
    image: baitImages.bait3,
    honey: 0,
    lockedHoney: 0,
  },

  // Fish items
  [ID_FISH_ITEMS.FISH_SMALL]: {
    label: "FISH_SMALL",
    category: ID_ITEM_CATEGORIES.FISH,
  },
  [ID_FISH_ITEMS.FISH_LARGE]: {
    label: "FISH_LARGE",
    category: ID_ITEM_CATEGORIES.FISH,
  },
  [ID_LOOTS.CATFISH]: {
    label: "Catfish",
    type: ID_RARE_TYPE.EPIC,
    image: fishImages.catfish,
  },

  // Chest items
  [ID_CHEST_ITEMS.CHEST_WOOD]: {
    label: "CHEST WOOD",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.CHEST,
    type: ID_RARE_TYPE.COMMON,
    image: chestImages.wood,
    honey: 0,
    lockedHoney: 0,
  },
  [ID_CHEST_ITEMS.CHEST_BRONZE]: {
    label: "CHEST BRONZE",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.CHEST,
    type: ID_RARE_TYPE.UNCOMMON,
    image: chestImages.bronze,
    honey: 0,
    lockedHoney: 0,
  },
  [ID_CHEST_ITEMS.CHEST_SILVER]: {
    label: "CHEST SILVER",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.CHEST,
    type: ID_RARE_TYPE.RARE,
    image: chestImages.silver,
    honey: 0,
    lockedHoney: 0,
  },
  [ID_CHEST_ITEMS.CHEST_GOLD]: {
    label: "CHEST GOLD",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.CHEST,
    type: ID_RARE_TYPE.EPIC,
    image: chestImages.gold,
    honey: 0,
    lockedHoney: 0,
  },

  // Potion items
  [ID_POTION_ITEMS.POTION_GROWTH_ELIXIR]: {
    label: "Growth Elixir",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.GROWTH_ELIXIR,
    type: ID_RARE_TYPE.COMMON,
    image: potionImages.growthElixir,
    honey: 0,
    lockedHoney: 0,
    exp: 75,
  },
  [ID_POTION_ITEMS.POTION_PESTICIDE]: {
    label: "Pesticide",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.PESTICIDE,
    type: ID_RARE_TYPE.UNCOMMON,
    image: potionImages.pesticide,
    honey: 0,
    lockedHoney: 0,
    exp: 250,
  },
  [ID_POTION_ITEMS.POTION_FERTILIZER]: {
    label: "Fertilizer",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.FERTILIZER,
    type: ID_RARE_TYPE.RARE,
    image: potionImages.fertilizer,
    honey: 0,
    lockedHoney: 0,
    exp: 2000,
  },

  [ID_FISHING_RODS.LVL1]: {
    label: "Fishing Rod 1",
    type: ID_RARE_TYPE.COMMON,
    image: fishingRodImages.lvl5,
  },
  [ID_FISHING_RODS.LVL2]: {
    label: "Fishing Rod 2",
    type: ID_RARE_TYPE.UNCOMMON,
    image: fishingRodImages.lvl5,
  },
  [ID_FISHING_RODS.LVL3]: {
    label: "Fishing Rod 3",
    type: ID_RARE_TYPE.RARE,
    image: fishingRodImages.lvl5,
  },
  [ID_FISHING_RODS.LVL4]: {
    label: "Fishing Rod 4",
    type: ID_RARE_TYPE.EPIC,
    image: fishingRodImages.lvl5,
  },
  [ID_FISHING_RODS.LVL5]: {
    label: "Fishing Rod 5",
    type: ID_RARE_TYPE.LEGENDARY,
    image: fishingRodImages.lvl5,
  },
};

// Merged ALL_ITEM_TREE from item_all for filtering/navigation
export const ALL_ITEM_TREE = [
  {
    id: "ALL",
    label: "All",
    children: [
      {
        id: ID_ITEM_CATEGORIES.CROP,
        label: "Crops",
        children: [
          {
            id: ID_CROP_CATEGORIES.PICO_SEED, label: "Pico", children: [
              { id: ID_SEEDS.POTATO, label: "Potato" },
              { id: ID_SEEDS.LETTUCE, label: "Lettuce" },
              { id: ID_SEEDS.CABBAGE, label: "Cabbage" },
              { id: ID_SEEDS.ONION, label: "Onion" },
              { id: ID_SEEDS.RADISH, label: "Radish" },
            ]
          },
          {
            id: ID_CROP_CATEGORIES.BASIC_SEED, label: "Basic", children: [
              { id: ID_SEEDS.WHEAT, label: "Wheat" },
              { id: ID_SEEDS.TOMATO, label: "Tomato" },
              { id: ID_SEEDS.CARROT, label: "Carrot" },
              { id: ID_SEEDS.CORN, label: "Corn" },
              { id: ID_SEEDS.PUMPKIN, label: "Pumpkin" },
              { id: ID_SEEDS.CHILI, label: "Chili" },
              { id: ID_SEEDS.PARSNIP, label: "Parsnip" },
              { id: ID_SEEDS.CELERY, label: "Celery" },
              { id: ID_SEEDS.BROCCOLI, label: "Broccoli" },
              { id: ID_SEEDS.CAULIFLOWER, label: "Cauliflower" },
              { id: ID_SEEDS.BERRY, label: "Berry" },
              { id: ID_SEEDS.GRAPES, label: "Grapes" },
            ]
          },
          {
            id: ID_CROP_CATEGORIES.PREMIUM_SEED, label: "Premium", children: [
              { id: ID_SEEDS.BANANA, label: "Banana" },
              { id: ID_SEEDS.MANGO, label: "Mango" },
              { id: ID_SEEDS.AVOCADO, label: "Avocado" },
              { id: ID_SEEDS.PINEAPPLE, label: "Pineapple" },
              { id: ID_SEEDS.BLUEBERRY, label: "Blueberry" },
              { id: ID_SEEDS.ARTICHOKE, label: "Artichoke" },
              { id: ID_SEEDS.PAPAYA, label: "Papaya" },
              { id: ID_SEEDS.FIG, label: "Fig" },
              { id: ID_SEEDS.LICHI, label: "Lichi" },
              { id: ID_SEEDS.LAVENDER, label: "Lavender" },
              { id: ID_SEEDS.DRAGON_FRUIT, label: "Dragon Fruit" },
            ]
          },
        ],
      },
      {
        id: ID_ITEM_CATEGORIES.POTION,
        label: "Potions",
        children: [
          {
            id: ID_POTION_CATEGORIES.GROWTH_ELIXIR, label: "Growth Elixirs", children: [
              { id: ID_POTIONS.GROWTH_ELIXIR, label: "Growth Elixir I" },
              { id: ID_POTIONS.GROWTH_ELIXIR_II, label: "Growth Elixir II" },
              { id: ID_POTIONS.GROWTH_ELIXIR_III, label: "Growth Elixir III" },
            ]
          },
          {
            id: ID_POTION_CATEGORIES.FERTILIZER, label: "Fertilizers", children: [
              { id: ID_POTIONS.FERTILIZER, label: "Fertilizer" },
              { id: ID_POTIONS.FERTILIZER_II, label: "Fertilizer II" },
              { id: ID_POTIONS.FERTILIZER_III, label: "Fertilizer III" },
            ]
          },
          {
            id: ID_POTION_CATEGORIES.PESTICIDE, label: "Pesticides", children: [
              { id: ID_POTIONS.PESTICIDE, label: "Pesticide" },
              { id: ID_POTIONS.PESTICIDE_II, label: "Pesticide II" },
              { id: ID_POTIONS.PESTICIDE_III, label: "Pesticide III" },
            ]
          }
        ]
      },
      {
        id: ID_ITEM_CATEGORIES.LOOT,
        label: "Loot",
        children: [
          {
            id: ID_LOOT_CATEGORIES.CHEST, label: "Chests", children: [
              { id: ID_LOOTS.WOODEN_CHEST, label: "Wooden Chest" },
              { id: ID_LOOTS.BRONZE_CHEST, label: "Bronze Chest" },
              { id: ID_LOOTS.SILVER_CHEST, label: "Silver Chest" },
              { id: ID_LOOTS.GOLDEN_CHEST, label: "Golden Chest" },
              { id: ID_LOOTS.PLATINUM_CHEST, label: "Platinum Chest" },
            ]
          },
          {
            id: ID_LOOT_CATEGORIES.BAIT, label: "Baits", children: [
              { id: ID_LOOTS.BAIT_I, label: "Bait I" },
              { id: ID_LOOTS.BAIT_II, label: "Bait II" },
              { id: ID_LOOTS.BAIT_III, label: "Bait III" }
            ]
          }
        ]
      }
    ],
  },
];
