import { baitImages, chestImages, fishImages, fishingRodImages, potionImages } from "./_baseimages";
import { ID_SEEDS, ID_PRODUCE_ITEMS, ID_BAIT_ITEMS, ID_FISH_ITEMS, ID_CHEST_ITEMS, ID_POTION_ITEMS, ID_CROP_CATEGORIES, ID_RARE_TYPE, ID_ITEM_CATEGORIES, ID_POTION_CATEGORIES, ID_LOOT_CATEGORIES, ID_FISHING_RODS, getRaritySeedId } from "./app_ids";

export const IMAGE_URL_CROP = "/public/images/crops/seeds.webp";
// All items data with categories
export const ALL_ITEMS = {
  // Seeds
  [ID_SEEDS.F_POTATO]: {
    id: ID_SEEDS.F_POTATO,
    label: "F.Potato",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.FEEBLE_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 29,
    honey: 0.5,
    lockedHoney: 0.75,
  },
  [ID_SEEDS.F_LETTUCE]: {
    id: ID_SEEDS.F_LETTUCE,
    label: "F.Lettuce",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.FEEBLE_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 30,
    honey: 0.9,
    lockedHoney: 1.35,
  },
  [ID_SEEDS.F_CABBAGE]: {
    id: ID_SEEDS.F_CABBAGE,
    label: "F.Celery",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.FEEBLE_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 31,
    honey: 1.2,
    lockedHoney: 1.8,
  },
  [ID_SEEDS.F_ONION]: {
    id: ID_SEEDS.F_ONION,
    label: "F.Onion",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.FEEBLE_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 32,
    honey: 2,
    lockedHoney: 3,
  },
  [ID_SEEDS.F_RADISH]: {
    id: ID_SEEDS.F_RADISH,
    label: "F.Radish",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.FEEBLE_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 33,
    honey: 5.4,
    lockedHoney: 8.1,
  },
  [ID_SEEDS.POTATO]: {
    id: ID_SEEDS.POTATO,
    label: "POTATO",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 24,
    honey: 10,
    lockedHoney: 15,
  },
  [ID_SEEDS.LETTUCE]: {
    id: ID_SEEDS.LETTUCE,
    label: "LETTUCE",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 26,
    honey: 18,
    lockedHoney: 27,
  },
  [ID_SEEDS.CABBAGE]: {
    id: ID_SEEDS.CABBAGE,
    label: "CELERY",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 25,
    honey: 24,
    lockedHoney: 36,
  },
  [ID_SEEDS.ONION]: {
    id: ID_SEEDS.ONION,
    label: "ONION",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 27,
    honey: 40,
    lockedHoney: 60,
  },
  [ID_SEEDS.RADISH]: {
    id: ID_SEEDS.RADISH,
    label: "RADISH",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 28,
    honey: 108,
    lockedHoney: 162,
  },
  [ID_SEEDS.TURNIP]: {
    id: ID_SEEDS.TURNIP,
    label: "TURNIP",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: '/images/crops/turnip.png',
    pos: -1,
    honey: 10,
    lockedHoney: 15,
  },
  [ID_SEEDS.WHEAT]: {
    id: ID_SEEDS.WHEAT,
    label: "WHEAT",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 1,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_SEEDS.TOMATO]: {
    id: ID_SEEDS.TOMATO,
    label: "TOMATO",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 2,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_SEEDS.CARROT]: {
    id: ID_SEEDS.CARROT,
    label: "CARROT",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 3,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_SEEDS.CORN]: {
    id: ID_SEEDS.CORN,
    label: "CORN",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 4,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_SEEDS.PUMPKIN]: {
    id: ID_SEEDS.PUMPKIN,
    label: "PUMPKIN",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 5,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_SEEDS.PEPPER]: {
    id: ID_SEEDS.PEPPER,
    label: "PEPPER",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 6,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_SEEDS.PARSNIP]: {
    id: ID_SEEDS.PARSNIP,
    label: "PARSNIP",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 7,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_SEEDS.CELERY]: {
    id: ID_SEEDS.CELERY,
    label: "CELERY",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 8,
    honey: 120,
    lockedHoney: 180,
  },
  [ID_SEEDS.BROCCOLI]: {
    id: ID_SEEDS.BROCCOLI,
    label: "BROCCOLI",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 9,
    honey: 120,
    lockedHoney: 180,
  },
  [ID_SEEDS.CAULIFLOWER]: {
    id: ID_SEEDS.CAULIFLOWER,
    label: "CAULIFLOWER",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 10,
    honey: 200,
    lockedHoney: 300,
  },
  [ID_SEEDS.BERRY]: {
    id: ID_SEEDS.BERRY,
    label: "BERRY",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 11,
    honey: 200,
    lockedHoney: 300,
  },
  [ID_SEEDS.GRAPES]: {
    id: ID_SEEDS.GRAPES,
    label: "GRAPES",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 12,
    honey: 540,
    lockedHoney: 810,
  },
  [ID_SEEDS.BOKCHOY]: {
    id: ID_SEEDS.BOKCHOY,
    label: "BOK CHOY",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 30,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_SEEDS.EGGPLANT]: {
    id: ID_SEEDS.EGGPLANT,
    label: "EGGPLANT",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 33,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_SEEDS.BANANA]: {
    id: ID_SEEDS.BANANA,
    label: "BANANA",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 13,
    honey: 400,
    lockedHoney: 600,
  },
  [ID_SEEDS.MANGO]: {
    id: ID_SEEDS.MANGO,
    label: "MANGO",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 14,
    honey: 400,
    lockedHoney: 600,
  },
  [ID_SEEDS.AVOCADO]: {
    id: ID_SEEDS.AVOCADO,
    label: "AVOCADO",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 15,
    honey: 400,
    lockedHoney: 600,
  },
  [ID_SEEDS.PINEAPPLE]: {
    id: ID_SEEDS.PINEAPPLE,
    label: "PINEAPPLE",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 16,
    honey: 720,
    lockedHoney: 1080,
  },
  [ID_SEEDS.BLUEBERRY]: {
    id: ID_SEEDS.BLUEBERRY,
    label: "BLUEBERRY",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 17,
    honey: 720,
    lockedHoney: 1080,
  },
  [ID_SEEDS.ARTICHOKE]: {
    id: ID_SEEDS.ARTICHOKE,
    label: "ARTICHOKE",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 18,
    honey: 720,
    lockedHoney: 1080,
  },
  [ID_SEEDS.PAPAYA]: {
    id: ID_SEEDS.PAPAYA,
    label: "PAPAYA",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 19,
    honey: 960,
    lockedHoney: 1440,
  },
  [ID_SEEDS.FIG]: {
    id: ID_SEEDS.FIG,
    label: "FIG",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 20,
    honey: 960,
    lockedHoney: 1440,
  },
  [ID_SEEDS.LICHI]: {
    id: ID_SEEDS.LICHI,
    label: "LICHI",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 21,
    honey: 1600,
    lockedHoney: 2400,
  },
  [ID_SEEDS.LAVENDER]: {
    id: ID_SEEDS.LAVENDER,
    label: "LAVENDER",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 22,
    honey: 1600,
    lockedHoney: 2400,
  },
  [ID_SEEDS.DRAGON_FRUIT]: {
    id: ID_SEEDS.DRAGON_FRUIT,
    label: "DRAGON_FRUIT",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 23,
    honey: 4400,
    lockedHoney: 6600,
  },
  [ID_SEEDS.POMEGRANATE]: {
    id: ID_SEEDS.POMEGRANATE,
    label: "POMEGRANATE",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 31,
    honey: 800,
    lockedHoney: 1200,
  },
  [ID_SEEDS.APPLE]: {
    id: ID_SEEDS.APPLE,
    label: "APPLE",
    category: ID_ITEM_CATEGORIES.SEED,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 32,
    honey: 800,
    lockedHoney: 1200,
  },

  // Produce items
  [ID_PRODUCE_ITEMS.POTATO]: {
    id: ID_PRODUCE_ITEMS.POTATO,
    label: "Potato",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 24,
    honey: 10,
    lockedHoney: 15,
  },
  [ID_PRODUCE_ITEMS.LETTUCE]: {
    id: ID_PRODUCE_ITEMS.LETTUCE,
    label: "Lettuce",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 26,
    honey: 18,
    lockedHoney: 27,
  },
  [ID_PRODUCE_ITEMS.CABBAGE]: {
    id: ID_PRODUCE_ITEMS.CABBAGE,
    label: "Celery",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 25,
    honey: 24,
    lockedHoney: 36,
  },
  [ID_PRODUCE_ITEMS.ONION]: {
    id: ID_PRODUCE_ITEMS.ONION,
    label: "Onion",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 27,
    honey: 40,
    lockedHoney: 60,
  },
  [ID_PRODUCE_ITEMS.RADISH]: {
    id: ID_PRODUCE_ITEMS.RADISH,
    label: "Radish",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 28,
    honey: 108,
    lockedHoney: 162,
  },
  [ID_PRODUCE_ITEMS.TURNIP]: {
    id: ID_PRODUCE_ITEMS.TURNIP,
    label: "Turnip",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PICO_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: '/images/crops/turnip.png',
    pos: -1,
    honey: 10,
    lockedHoney: 15,
  },
  [ID_PRODUCE_ITEMS.WHEAT]: {
    id: ID_PRODUCE_ITEMS.WHEAT,
    label: "Wheat",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 1,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_PRODUCE_ITEMS.TOMATO]: {
    id: ID_PRODUCE_ITEMS.TOMATO,
    label: "Tomato",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 2,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_PRODUCE_ITEMS.CARROT]: {
    id: ID_PRODUCE_ITEMS.CARROT,
    label: "Carrot",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 3,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_PRODUCE_ITEMS.CORN]: {
    id: ID_PRODUCE_ITEMS.CORN,
    label: "Corn",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 4,
    honey: 50,
    lockedHoney: 75,
  },
  [ID_PRODUCE_ITEMS.PUMPKIN]: {
    id: ID_PRODUCE_ITEMS.PUMPKIN,
    label: "Pumpkin",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 5,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_PRODUCE_ITEMS.PEPPER]: {
    id: ID_PRODUCE_ITEMS.PEPPER,
    label: "Pepper",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 6,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_PRODUCE_ITEMS.PARSNAP]: {
    id: ID_PRODUCE_ITEMS.PARSNAP,
    label: "Parnship",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 7,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_PRODUCE_ITEMS.CELERY]: {
    id: ID_PRODUCE_ITEMS.CELERY,
    label: "Celery",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 8,
    honey: 120,
    lockedHoney: 180,
  },
  [ID_PRODUCE_ITEMS.BROCCOLI]: {
    id: ID_PRODUCE_ITEMS.BROCCOLI,
    label: "Broccoli",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 9,
    honey: 120,
    lockedHoney: 180,
  },
  [ID_PRODUCE_ITEMS.CAULIFLOWER]: {
    id: ID_PRODUCE_ITEMS.CAULIFLOWER,
    label: "Cauliflower",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 10,
    honey: 200,
    lockedHoney: 300,
  },
  [ID_PRODUCE_ITEMS.BERRY]: {
    id: ID_PRODUCE_ITEMS.BERRY,
    label: "Berry",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 11,
    honey: 200,
    lockedHoney: 300,
  },
  [ID_PRODUCE_ITEMS.GRAPES]: {
    id: ID_PRODUCE_ITEMS.GRAPES,
    label: "Grapes",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 12,
    honey: 540,
    lockedHoney: 810,
  },
  [ID_PRODUCE_ITEMS.BOKCHOY]: {
    id: ID_PRODUCE_ITEMS.BOKCHOY,
    label: "Bok Choy",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 30,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_PRODUCE_ITEMS.EGGPLANT]: {
    id: ID_PRODUCE_ITEMS.EGGPLANT,
    label: "Eggplant",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.BASIC_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 33,
    honey: 90,
    lockedHoney: 135,
  },
  [ID_PRODUCE_ITEMS.BANANA]: {
    id: ID_PRODUCE_ITEMS.BANANA,
    label: "Banana",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 13,
    honey: 400,
    lockedHoney: 600,
  },
  [ID_PRODUCE_ITEMS.MANGO]: {
    id: ID_PRODUCE_ITEMS.MANGO,
    label: "Mango",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 14,
    honey: 400,
    lockedHoney: 600,
  },
  [ID_PRODUCE_ITEMS.AVOCADO]: {
    id: ID_PRODUCE_ITEMS.AVOCADO,
    label: "Avocado",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 15,
    honey: 400,
    lockedHoney: 600,
  },
  [ID_PRODUCE_ITEMS.PINEAPPLE]: {
    id: ID_PRODUCE_ITEMS.PINEAPPLE,
    label: "Pineapple",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 16,
    honey: 720,
    lockedHoney: 1080,
  },
  [ID_PRODUCE_ITEMS.BLUEBERRY]: {
    id: ID_PRODUCE_ITEMS.BLUEBERRY,
    label: "Blueberry",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 17,
    honey: 720,
    lockedHoney: 1080,
  },
  [ID_PRODUCE_ITEMS.ARTICHOKE]: {
    id: ID_PRODUCE_ITEMS.ARTICHOKE,
    label: "Artichoke",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.UNCOMMON,
    image: IMAGE_URL_CROP,
    pos: 18,
    honey: 720,
    lockedHoney: 1080,
  },
  [ID_PRODUCE_ITEMS.PAPAYA]: {
    id: ID_PRODUCE_ITEMS.PAPAYA,
    label: "Papaya",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 19,
    honey: 960,
    lockedHoney: 1440,
  },
  [ID_PRODUCE_ITEMS.FIG]: {
    id: ID_PRODUCE_ITEMS.FIG,
    label: "Fig",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.RARE,
    image: IMAGE_URL_CROP,
    pos: 20,
    honey: 960,
    lockedHoney: 1440,
  },
  [ID_PRODUCE_ITEMS.LYCHEE]: {
    id: ID_PRODUCE_ITEMS.LYCHEE,
    label: "Lichi",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 21,
    honey: 1600,
    lockedHoney: 2400,
  },
  [ID_PRODUCE_ITEMS.LAVENDER]: {
    id: ID_PRODUCE_ITEMS.LAVENDER,
    label: "Lavender",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.EPIC,
    image: IMAGE_URL_CROP,
    pos: 22,
    honey: 1600,
    lockedHoney: 2400,
  },
  [ID_PRODUCE_ITEMS.DRAGONFRUIT]: {
    id: ID_PRODUCE_ITEMS.DRAGONFRUIT,
    label: "Dragon Fruit",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.LEGENDARY,
    image: IMAGE_URL_CROP,
    pos: 23,
    honey: 4400,
    lockedHoney: 6600,
  },
  [ID_PRODUCE_ITEMS.POMEGRANATE]: {
    id: ID_PRODUCE_ITEMS.POMEGRANATE,
    label: "Pomegranate",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 31,
    honey: 800,
    lockedHoney: 1200,
  },
  [ID_PRODUCE_ITEMS.APPLE]: {
    id: ID_PRODUCE_ITEMS.APPLE,
    label: "Apple",
    category: ID_ITEM_CATEGORIES.PRODUCE,
    subCategory: ID_CROP_CATEGORIES.PREMIUM_SEED,
    type: ID_RARE_TYPE.COMMON,
    image: IMAGE_URL_CROP,
    pos: 32,
    honey: 800,
    lockedHoney: 1200,
  },

  // Bait items
  [ID_BAIT_ITEMS.BAIT_1]: {
    id: ID_BAIT_ITEMS.BAIT_1,
    label: "Bait I",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.BAIT,
    pos: -1,
    type: ID_RARE_TYPE.COMMON,
    image: baitImages.bait1,
    honey: 0,
    lockedHoney: 0,
  },
  [ID_BAIT_ITEMS.BAIT_2]: {
    label: "Bait II",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.BAIT,
    pos: -1,
    type: ID_RARE_TYPE.UNCOMMON,
    image: baitImages.bait2,
    honey: 0,
    lockedHoney: 0,
  },
  [ID_BAIT_ITEMS.BAIT_3]: {
    label: "Bait III",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.BAIT,
    pos: -1,
    type: ID_RARE_TYPE.RARE,
    image: baitImages.bait3,
    honey: 0,
    lockedHoney: 0,
  },

  // Fish items
  [ID_FISH_ITEMS.FISH_SMALL]: {
    label: "FISH_SMALL",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.FISH,
    type: ID_RARE_TYPE.EPIC,
    image: fishImages.catfish,
    pos: -1,
  },
  [ID_FISH_ITEMS.FISH_LARGE]: {
    label: "FISH_LARGE",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.FISH,
    type: ID_RARE_TYPE.EPIC,
    image: fishImages.catfish,
    pos: -1,
  },
  [ID_FISH_ITEMS.ANCHOVY]: {
    label: "Anchovy",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.FISH,
    type: ID_RARE_TYPE.COMMON,
    image: fishImages.anchovy,
    pos: -1,
  },
  [ID_FISH_ITEMS.SARDINE]: {
    label: "Sardin",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.FISH,
    type: ID_RARE_TYPE.COMMON,
    image: fishImages.sardine,
    pos: -1,
  },
  [ID_FISH_ITEMS.HERRING]: {
    label: "Herring",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.FISH,
    type: ID_RARE_TYPE.UNCOMMON,
    image: fishImages.herring,
    pos: -1,
  },
  [ID_FISH_ITEMS.SMALL_TROUT]: {
    label: "Small Trout",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.FISH,
    type: ID_RARE_TYPE.UNCOMMON,
    image: fishImages.smallTrout,
    pos: -1,
  },
  [ID_FISH_ITEMS.YELLOW_PERCH]: {
    label: "Yellow Perch",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.FISH,
    type: ID_RARE_TYPE.RARE,
    image: fishImages.yellowPerch,
    pos: -1,
  },
  [ID_FISH_ITEMS.SALMON]: {
    label: "Salmon",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.FISH,
    type: ID_RARE_TYPE.RARE,
    image: fishImages.salmon,
    pos: -1,
  },
  [ID_FISH_ITEMS.ORANGE_ROUGHY]: {
    label: "Orange Roughy",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.FISH,
    type: ID_RARE_TYPE.EPIC,
    image: fishImages.orangeRoughy,
    pos: -1,
  },
  [ID_FISH_ITEMS.CATFISH]: {
    label: "Catfish",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.FISH,
    type: ID_RARE_TYPE.EPIC,
    image: fishImages.catfish,
    pos: -1,
  },
  [ID_FISH_ITEMS.SMALL_SHARK]: {
    label: "Small Shark",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.FISH,
    type: ID_RARE_TYPE.LEGENDARY,
    image: fishImages.smallShark,
    pos: -1,
  },
  [ID_FISH_ITEMS.NORMAL_FISH]: {
    label: "Normal fish",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.FISH,
    type: ID_RARE_TYPE.COMMON,
    image: "/images/fish/Normal Ocean Fish (2).png",
    pos: -1,
  },

  // Chest items
  [ID_CHEST_ITEMS.CHEST_WOOD]: {
    label: "Wooden Chest",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.CHEST,
    type: ID_RARE_TYPE.COMMON,
    image: chestImages.wood,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
  },
  [ID_CHEST_ITEMS.CHEST_BRONZE]: {
    label: "Bronze Chest",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.CHEST,
    type: ID_RARE_TYPE.RARE,
    image: chestImages.bronze,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
  },
  [ID_CHEST_ITEMS.CHEST_SILVER]: {
    label: "Silver Chest",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.CHEST,
    type: ID_RARE_TYPE.EPIC,
    image: chestImages.silver,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
  },
  [ID_CHEST_ITEMS.CHEST_GOLD]: {
    label: "Golden Chest",
    category: ID_ITEM_CATEGORIES.LOOT,
    subCategory: ID_LOOT_CATEGORIES.CHEST,
    type: ID_RARE_TYPE.LEGENDARY,
    image: chestImages.gold,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
  },

  // Potion items
  [ID_POTION_ITEMS.POTION_GROWTH_ELIXIR]: {
    label: "Growth Elixir",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.GROWTH_ELIXIR,
    type: ID_RARE_TYPE.COMMON,
    image: potionImages.growthElixir,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
    exp: 75,
  },
  [ID_POTION_ITEMS.POTION_GROWTH_ELIXIR_II]: {
    label: "Growth Elixir II",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.GROWTH_ELIXIR,
    type: ID_RARE_TYPE.UNCOMMON,
    image: potionImages.growthElixir_II,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
    exp: 75,
  },
  [ID_POTION_ITEMS.POTION_GROWTH_ELIXIR_III]: {
    label: "Growth Elixir III",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.GROWTH_ELIXIR,
    type: ID_RARE_TYPE.RARE,
    image: potionImages.growthElixir_III,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
    exp: 75,
  },
  [ID_POTION_ITEMS.POTION_FERTILIZER]: {
    label: "Fertilizer",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.FERTILIZER,
    type: ID_RARE_TYPE.RARE,
    image: potionImages.fertilizer,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
    exp: 2000,
  },
  [ID_POTION_ITEMS.POTION_FERTILIZER_II]: {
    label: "Fertilizer II",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.FERTILIZER,
    type: ID_RARE_TYPE.EPIC,
    image: potionImages.fertilizer_II,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
    exp: 2000,
  },
  [ID_POTION_ITEMS.POTION_FERTILIZER_III]: {
    label: "Fertilizer",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.FERTILIZER,
    type: ID_RARE_TYPE.LEGENDARY,
    image: potionImages.fertilizer_III,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
    exp: 2000,
  },
  [ID_POTION_ITEMS.POTION_PESTICIDE]: {
    label: "Pesticide",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.PESTICIDE,
    type: ID_RARE_TYPE.UNCOMMON,
    image: potionImages.pesticide,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
    exp: 250,
  },
  [ID_POTION_ITEMS.POTION_PESTICIDE_II]: {
    label: "Pesticide II",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.PESTICIDE,
    type: ID_RARE_TYPE.RARE,
    image: potionImages.pesticide_II,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
    exp: 250,
  },
  [ID_POTION_ITEMS.POTION_PESTICIDE_III]: {
    label: "Pesticide III",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.PESTICIDE,
    type: ID_RARE_TYPE.EPIC,
    image: potionImages.pesticide_III,
    pos: -1,
    honey: 0,
    lockedHoney: 0,
    exp: 250,
  },
  [ID_POTION_ITEMS.SCARECROW]: {
    label: "Scarecrow",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.SCARECROW,
    type: ID_RARE_TYPE.EPIC,
    image: "/images/scarecrow/Scarecrow1.png",
    pos: -1,
    honey: 0,
    lockedHoney: 0,
  },
  [ID_POTION_ITEMS.LADYBUG]: {
    label: "Ladybug",
    category: ID_ITEM_CATEGORIES.POTION,
    subCategory: ID_POTION_CATEGORIES.LADYBUG,
    type: ID_RARE_TYPE.EPIC,
    image: "/images/ladybug/ladybug.jpg",
    pos: -1,
    honey: 0,
    lockedHoney: 0,
  },
  [ID_FISHING_RODS.LVL1]: {
    label: "Fishing Rod 1",
    type: ID_RARE_TYPE.COMMON,
    image: fishingRodImages.lvl5,
  },
  [ID_FISHING_RODS.LVL2]: {
    label: "Fishing Rod 2",
    type: ID_RARE_TYPE.UNCOMMON,
    image: fishingRodImages.lvl5,
  },
  [ID_FISHING_RODS.LVL3]: {
    label: "Fishing Rod 3",
    type: ID_RARE_TYPE.RARE,
    image: fishingRodImages.lvl5,
  },
  [ID_FISHING_RODS.LVL4]: {
    label: "Fishing Rod 4",
    type: ID_RARE_TYPE.EPIC,
    image: fishingRodImages.lvl5,
  },
  [ID_FISHING_RODS.LVL5]: {
    label: "Fishing Rod 5",
    type: ID_RARE_TYPE.LEGENDARY,
    image: fishingRodImages.lvl5,
  },
};

// Generate rarity variant entries for all Pico, Basic, and Premium seeds.
// Each variant shares the same sprite/label as its base seed but has a different type and produceCount.
const _RARITY_VARIANT_SEEDS = [
  ID_SEEDS.POTATO, ID_SEEDS.LETTUCE, ID_SEEDS.CABBAGE, ID_SEEDS.ONION, ID_SEEDS.RADISH, ID_SEEDS.TURNIP,
  ID_SEEDS.WHEAT, ID_SEEDS.TOMATO, ID_SEEDS.CARROT, ID_SEEDS.CORN,
  ID_SEEDS.PUMPKIN, ID_SEEDS.PEPPER, ID_SEEDS.PARSNIP,
  ID_SEEDS.CELERY, ID_SEEDS.BROCCOLI,
  ID_SEEDS.CAULIFLOWER, ID_SEEDS.BERRY, ID_SEEDS.GRAPES, ID_SEEDS.BOKCHOY, ID_SEEDS.EGGPLANT,
  ID_SEEDS.BANANA, ID_SEEDS.MANGO, ID_SEEDS.AVOCADO,
  ID_SEEDS.PINEAPPLE, ID_SEEDS.BLUEBERRY, ID_SEEDS.ARTICHOKE,
  ID_SEEDS.PAPAYA, ID_SEEDS.FIG,
  ID_SEEDS.LICHI, ID_SEEDS.LAVENDER, ID_SEEDS.DRAGON_FRUIT, ID_SEEDS.POMEGRANATE, ID_SEEDS.APPLE,
];
const _RARITY_VARIANTS = [
  { type: ID_RARE_TYPE.UNCOMMON, level: 2, produceCount: 2 },
  { type: ID_RARE_TYPE.RARE,     level: 3, produceCount: 3 },
  { type: ID_RARE_TYPE.EPIC,     level: 4, produceCount: 4 },
  { type: ID_RARE_TYPE.LEGENDARY, level: 5, produceCount: 5 },
];
_RARITY_VARIANT_SEEDS.forEach(baseId => {
  _RARITY_VARIANTS.forEach(({ type, level, produceCount }) => {
    const variantId = getRaritySeedId(baseId, level);
    const base = ALL_ITEMS[baseId];
    if (base) ALL_ITEMS[variantId] = { ...base, id: variantId, type, produceCount };
  });
});

// Merged ALL_ITEM_TREE from item_all for filtering/navigation
export const ALL_ITEM_TREE = [
  {
    id: "ALL",
    label: "All",
    children: [
      {
        id: ID_ITEM_CATEGORIES.PRODUCE,
        label: "Crops",
        children: [
          {
            id: ID_CROP_CATEGORIES.PICO_SEED, label: "Pico", children: [
              { id: ID_SEEDS.POTATO, label: "Potato" },
              { id: ID_SEEDS.LETTUCE, label: "Lettuce" },
              { id: ID_SEEDS.CABBAGE, label: "Celery" },
              { id: ID_SEEDS.ONION, label: "Onion" },
              { id: ID_SEEDS.RADISH, label: "Radish" },
              { id: ID_SEEDS.TURNIP, label: "Turnip" },
            ]
          },
          {
            id: ID_CROP_CATEGORIES.BASIC_SEED, label: "Basic", children: [
              { id: ID_SEEDS.WHEAT, label: "Wheat" },
              { id: ID_SEEDS.TOMATO, label: "Tomato" },
              { id: ID_SEEDS.CARROT, label: "Carrot" },
              { id: ID_SEEDS.CORN, label: "Corn" },
              { id: ID_SEEDS.PUMPKIN, label: "Pumpkin" },
              { id: ID_SEEDS.PEPPER, label: "Pepper" },
              { id: ID_SEEDS.PARSNIP, label: "Parsnip" },
              { id: ID_SEEDS.CELERY, label: "Celery" },
              { id: ID_SEEDS.BROCCOLI, label: "Broccoli" },
              { id: ID_SEEDS.CAULIFLOWER, label: "Cauliflower" },
              { id: ID_SEEDS.BERRY, label: "Berry" },
              { id: ID_SEEDS.GRAPES, label: "Grapes" },
              { id: ID_SEEDS.BOKCHOY, label: "Bok Choy" },
              { id: ID_SEEDS.EGGPLANT, label: "Eggplant" },
            ]
          },
          {
            id: ID_CROP_CATEGORIES.PREMIUM_SEED, label: "Premium", children: [
              { id: ID_SEEDS.BANANA, label: "Banana" },
              { id: ID_SEEDS.MANGO, label: "Mango" },
              { id: ID_SEEDS.AVOCADO, label: "Avocado" },
              { id: ID_SEEDS.PINEAPPLE, label: "Pineapple" },
              { id: ID_SEEDS.BLUEBERRY, label: "Blueberry" },
              { id: ID_SEEDS.ARTICHOKE, label: "Artichoke" },
              { id: ID_SEEDS.PAPAYA, label: "Papaya" },
              { id: ID_SEEDS.FIG, label: "Fig" },
              { id: ID_SEEDS.LICHI, label: "Lichi" },
              { id: ID_SEEDS.LAVENDER, label: "Lavender" },
              { id: ID_SEEDS.DRAGON_FRUIT, label: "Dragon Fruit" },
              { id: ID_SEEDS.POMEGRANATE, label: "Pomegranate" },
              { id: ID_SEEDS.APPLE, label: "Apple" },
            ]
          },
        ],
      },
      {
        id: ID_ITEM_CATEGORIES.POTION,
        label: "Potions",
        children: [
          {
            id: ID_POTION_CATEGORIES.GROWTH_ELIXIR, label: "Growth Elixirs", children: [
              { id: ID_POTION_ITEMS.GROWTH_ELIXIR, label: "Growth Elixir I" },
              { id: ID_POTION_ITEMS.GROWTH_ELIXIR_II, label: "Growth Elixir II" },
              { id: ID_POTION_ITEMS.GROWTH_ELIXIR_III, label: "Growth Elixir III" },
            ]
          },
          {
            id: ID_POTION_CATEGORIES.FERTILIZER, label: "Fertilizers", children: [
              { id: ID_POTION_ITEMS.FERTILIZER, label: "Fertilizer" },
              { id: ID_POTION_ITEMS.FERTILIZER_II, label: "Fertilizer II" },
              { id: ID_POTION_ITEMS.FERTILIZER_III, label: "Fertilizer III" },
            ]
          },
          {
            id: ID_POTION_CATEGORIES.PESTICIDE, label: "Pesticides", children: [
              { id: ID_POTION_ITEMS.PESTICIDE, label: "Pesticide" },
              { id: ID_POTION_ITEMS.PESTICIDE_II, label: "Pesticide II" },
              { id: ID_POTION_ITEMS.PESTICIDE_III, label: "Pesticide III" },
            ]
          },
          {
            id: ID_POTION_CATEGORIES.SCARECROW, label: "Scarecrows", children: [
              { id: ID_POTION_ITEMS.SCARECROW, label: "Scarecrow" },
            ]
          },
          {
            id: ID_POTION_CATEGORIES.LADYBUG, label: "Ladybugs", children: [
              { id: ID_POTION_ITEMS.LADYBUG, label: "Ladybug" },
            ]
          }
        ]
      },
      {
        id: ID_ITEM_CATEGORIES.LOOT,
        label: "Loot",
        children: [
          {
            id: ID_LOOT_CATEGORIES.CHEST, label: "Chests", children: [
              { id: ID_CHEST_ITEMS.WOODEN_CHEST, label: "Wooden Chest" },
              { id: ID_CHEST_ITEMS.BRONZE_CHEST, label: "Bronze Chest" },
              { id: ID_CHEST_ITEMS.SILVER_CHEST, label: "Silver Chest" },
              { id: ID_CHEST_ITEMS.GOLDEN_CHEST, label: "Golden Chest" },
            ]
          },
          {
            id: ID_LOOT_CATEGORIES.BAIT, label: "Baits", children: [
              { id: ID_BAIT_ITEMS.BAIT_I, label: "Bait I" },
              { id: ID_BAIT_ITEMS.BAIT_II, label: "Bait II" },
              { id: ID_BAIT_ITEMS.BAIT_III, label: "Bait III" }
            ]
          }
        ]
      }
    ],
  },
];
