export const SEEDS = {
  USER_DATA: 'user_data',
  RECEIVER: 'receiver',
  BANKER_DATA: 'banker_data',
  BANK_VAULT: 'bank_vault',
  GAME_VAULT: 'game_vault',
  GAME_REGISTRY: 'game_registry',
  REQUEST: 'request',
  FISHING_REQUEST: 'fishing_request',
  LISTING: 'listing',
  MARKET_DATA: 'market_data',
  REF_CODE: 'ref_code',
  EPOCH_TOP5: 'epoch_top5',
  ITEM_MINT: 'item_mint',
  ITEM_MINT_AUTH: 'mint_auth_items',
  GAME_TOKEN_MINT_AUTH: 'mint_auth_game',
};
